id: IBCAF869E
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-27T01:19:55+00:00'
last_modified: '2022-06-09T04:40:14.239350+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W00KG01590
  title: སེངྒེ་སྒྲའི་སྒྲུབ་ཐབས་རྗེས་སྣང་དང་བཅས་པ
  author: ''
  access: http://purl.bdrc.io/admindata/AccessRestrictedSealed
  restrictedInChina: false
  base:
    9CCC:
      image_group_id: I00KG02834
      title: Volume 1 of seng ge sgra'i sgrub thabs rjes snang dang bcas pa
      total_pages: 8
      order: 1
      base_file: 9CCC.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
