id: P008124
initial_creation_type: ocr
source_metadata:
  id: bdr:W00KG01590
  title: སེངྒེ་སྒྲའི་སྒྲུབ་ཐབས་རྗེས་སྣང་དང་བཅས་པ
  author: ''
  volumes:
    9535b06dafe54daf809d7143e445e285:
      image_group_id: I00KG02834
      title: ''
      volume_number: 1
      total_pages: 8
ebook_metadata:
  title: སེངྒེ་སྒྲའི་སྒྲུབ་ཐབས་རྗེས་སྣང་དང་བཅས་པ
  author: ''
  sku: P008124
  cover: cover.jpg
  layers:
  - pagination
