id: P008124
initial_creation_type: ocr
created_at: 27/03/2020
last_modified_at: 2021-12-17 13:03:16.377643
source_metadata:
  id: bdr:W00KG01590
  title: སེངྒེ་སྒྲའི་སྒྲུབ་ཐབས་རྗེས་སྣང་དང་བཅས་པ
  author: ''
  volumes:
    4b466b5e26404b9f8a69b376427052ce:
      image_group_id: I00KG02834
      title: Volume 1 of seng ge sgra'i sgrub thabs rjes snang dang bcas pa
      volume_number: 1
      total_pages: 8
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessRestrictedSealed
  restrictedInChina: false
